/* The following code was generated by JFlex 1.6.1 */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/Universidad/3º/Segundo Cuatrimestre/Procesadores de lenguaje/Práctica - PL/-PL-Practica1/LSpecification/lexical_specification.flex</tt>
 */
class AnalizadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comment = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\5\1\7\1\7\1\6\22\0\1\17\3\0\1\3"+
    "\2\0\1\11\1\12\1\15\1\13\1\1\1\60\1\1\1\60\1\0"+
    "\12\2\1\57\1\60\1\62\1\61\1\63\2\0\1\53\1\4\1\55"+
    "\1\4\1\50\1\4\1\51\1\56\1\45\2\10\1\54\1\10\1\46"+
    "\3\10\1\52\1\10\1\47\6\10\4\0\1\10\1\0\1\24\1\26"+
    "\1\33\1\32\1\27\1\40\1\23\1\42\1\30\2\10\1\44\1\25"+
    "\1\31\1\22\1\20\1\10\1\21\1\34\1\35\1\37\1\36\1\43"+
    "\1\10\1\41\1\10\1\14\1\0\1\16\7\0\1\7\u1fa2\0\1\7"+
    "\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\2\5\2\1"+
    "\2\2\1\6\21\1\1\4\2\2\1\1\1\7\1\3"+
    "\2\0\2\4\1\0\2\10\1\0\2\10\1\2\17\10"+
    "\1\3\2\0\1\11\1\12\1\11\1\4\1\13\14\10"+
    "\1\12\1\11\1\12\22\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\150"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\150\0\150\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410"+
    "\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u064c\0\150\0\u0680\0\u06b4\0\u06e8\0\u071c"+
    "\0\u0104\0\u0750\0\u0138\0\u01a0\0\u0784\0\u07b8\0\u07ec\0\u01a0"+
    "\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c"+
    "\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c"+
    "\0\u0b60\0\u0b94\0\u06e8\0\u0750\0\u071c\0\u0bc8\0\u0784\0\u0bfc"+
    "\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\u0b60\0\u0b60\0\u0b94\0\u0e6c\0\u0ea0"+
    "\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040"+
    "\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\14\1\15\1\16\1\15\1\3\1\10"+
    "\1\17\1\20\1\21\1\12\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\12\1\32\1\33\1\12"+
    "\1\34\2\12\1\35\1\12\1\36\2\12\1\7\1\12"+
    "\1\37\1\7\1\12\1\40\1\12\1\41\2\15\1\42"+
    "\1\41\13\3\1\43\2\3\1\44\45\3\66\0\1\45"+
    "\1\0\1\46\43\0\1\46\2\0\1\46\1\0\1\46"+
    "\6\0\2\47\1\5\1\47\1\50\3\0\40\47\1\50"+
    "\2\47\1\50\1\47\1\50\6\47\2\0\1\51\1\0"+
    "\1\51\43\0\1\51\2\0\1\51\1\0\1\51\6\0"+
    "\2\52\1\53\1\52\1\53\3\0\1\54\7\52\30\54"+
    "\1\53\2\54\1\53\1\54\1\53\1\54\5\52\5\0"+
    "\1\10\60\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\37\54\5\0\64\55\13\0\1\16\52\0\1\54\1\0"+
    "\1\54\3\0\1\54\7\0\1\54\1\56\35\54\7\0"+
    "\1\54\1\0\1\54\3\0\1\54\7\0\7\54\1\57"+
    "\27\54\7\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\1\54\1\60\16\54\1\60\16\54\7\0\1\54\1\0"+
    "\1\54\3\0\1\54\7\0\1\54\1\61\7\54\1\62"+
    "\25\54\7\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\2\54\1\62\34\54\7\0\1\54\1\0\1\54\3\0"+
    "\1\54\7\0\7\54\1\63\27\54\7\0\1\54\1\0"+
    "\1\54\3\0\1\54\7\0\11\54\1\62\25\54\7\0"+
    "\1\54\1\0\1\54\3\0\1\54\7\0\20\54\1\60"+
    "\16\54\7\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\2\54\1\64\34\54\7\0\1\54\1\0\1\54\3\0"+
    "\1\54\7\0\2\54\1\60\5\54\1\65\26\54\7\0"+
    "\1\54\1\0\1\54\3\0\1\54\7\0\2\54\1\66"+
    "\1\54\1\67\32\54\7\0\1\54\1\0\1\54\3\0"+
    "\1\54\7\0\2\54\1\60\16\54\1\70\1\71\14\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\4\54"+
    "\1\72\32\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\2\54\1\72\14\54\1\73\17\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\22\54\1\74\14\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\26\54"+
    "\1\75\10\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\30\54\1\76\6\54\5\0\2\52\1\53\1\52"+
    "\1\53\3\0\1\54\7\52\30\54\1\53\2\54\1\53"+
    "\1\54\1\53\1\77\5\52\61\0\1\15\63\0\1\15"+
    "\1\0\1\15\15\0\1\44\46\0\2\47\1\100\1\47"+
    "\1\101\3\0\40\47\1\101\2\47\1\101\1\47\1\101"+
    "\6\47\2\52\1\102\1\52\1\102\3\0\40\52\1\102"+
    "\2\52\1\102\1\52\1\102\6\52\2\0\1\103\1\0"+
    "\1\104\43\0\1\104\2\0\1\104\1\0\1\104\6\0"+
    "\2\52\1\105\1\52\1\106\3\0\40\52\1\106\2\52"+
    "\1\106\1\52\1\106\6\52\2\0\1\104\1\0\1\104"+
    "\43\0\1\104\2\0\1\104\1\0\1\104\6\0\11\55"+
    "\1\107\52\55\2\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\2\54\1\110\34\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\13\54\1\111\23\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\1\54\1\112\35\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\12\54"+
    "\1\60\24\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\3\54\1\113\33\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\15\54\1\60\21\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\16\54\1\60\20\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\11\54"+
    "\1\114\25\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\14\54\1\115\22\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\1\115\36\54\7\0\1\54\1\0"+
    "\1\54\3\0\1\54\7\0\7\54\1\116\27\54\7\0"+
    "\1\54\1\0\1\54\3\0\1\54\7\0\1\54\1\60"+
    "\35\54\7\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\11\54\1\117\25\54\7\0\1\54\1\0\1\54\3\0"+
    "\1\54\7\0\10\54\1\120\26\54\7\0\1\54\1\0"+
    "\1\54\3\0\1\54\7\0\27\54\1\121\7\54\7\0"+
    "\1\54\1\0\1\54\3\0\1\54\7\0\33\54\1\122"+
    "\3\54\7\0\1\54\1\0\1\54\3\0\1\54\7\0"+
    "\33\54\1\123\3\54\5\0\2\47\1\100\1\47\1\124"+
    "\3\0\40\47\1\124\2\47\1\124\1\47\1\124\6\47"+
    "\2\52\1\125\1\52\1\126\3\0\40\52\1\126\2\52"+
    "\1\126\1\52\1\126\10\52\1\126\1\52\1\126\3\0"+
    "\40\52\1\126\2\52\1\126\1\52\1\126\10\52\1\106"+
    "\1\52\1\106\3\0\40\52\1\106\2\52\1\106\1\52"+
    "\1\106\6\52\2\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\3\54\1\127\7\54\1\130\23\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\2\54\1\131\34\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\4\54"+
    "\1\132\32\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\10\54\1\116\26\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\14\54\1\64\22\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\7\54\1\60\27\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\11\54"+
    "\1\60\25\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\13\54\1\133\23\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\24\54\1\115\12\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\30\54\1\134\6\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\34\54"+
    "\1\60\2\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\32\54\1\135\4\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\1\54\1\136\35\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\7\54\1\137\27\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\1\54"+
    "\1\62\35\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\21\54\1\60\15\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\15\54\1\140\21\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\31\54\1\141\5\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\33\54"+
    "\1\142\3\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\4\54\1\143\32\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\12\54\1\144\24\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\10\54\1\145\26\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\30\54"+
    "\1\146\6\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\35\54\1\147\1\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\5\54\1\60\31\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\17\54\1\150\17\54"+
    "\7\0\1\54\1\0\1\54\3\0\1\54\7\0\2\54"+
    "\1\116\34\54\7\0\1\54\1\0\1\54\3\0\1\54"+
    "\7\0\32\54\1\60\4\54\7\0\1\54\1\0\1\54"+
    "\3\0\1\54\7\0\27\54\1\141\7\54\7\0\1\54"+
    "\1\0\1\54\3\0\1\54\7\0\1\54\1\115\35\54"+
    "\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4628];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\1\11\4\1\2\11\25\1\1\11"+
    "\1\1\2\0\2\1\1\0\2\1\1\0\23\1\2\0"+
    "\46\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            }
          case 12: break;
          case 2: 
            { System.out.println("Token: " + yytext());
            }
          case 13: break;
          case 3: 
            { System.out.println("Constante entera: " + yytext());
            }
          case 14: break;
          case 4: 
            { System.out.println("Constante Entera Hexa: " + yytext());
            }
          case 15: break;
          case 5: 
            { 
            }
          case 16: break;
          case 6: 
            { System.out.println("Inicio de comentario");
			yybegin(comment);
            }
          case 17: break;
          case 7: 
            { System.out.println("Fin de comentario");
			yybegin(YYINITIAL);
            }
          case 18: break;
          case 8: 
            { System.out.println("Identificador: " + yytext());
            }
          case 19: break;
          case 9: 
            { System.out.println("Constante Real: " + yytext());
            }
          case 20: break;
          case 10: 
            { System.out.println("Constante Real Hexa: " + yytext());
            }
          case 21: break;
          case 11: 
            { System.out.println("Cadena de caracteres" + yytext());
            }
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalizadorLexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalizadorLexico scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalizadorLexico(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
