/* The following code was generated by JFlex 1.6.1 */


/********************************************************************/
/********************************************************************/
/***** 		Autores: Carlos Ruiz Ballesteros (GII + MAT)		*****/
/*****			 Hector Ruiz Poveda	(GII + GIS)      			*****/
/********************************************************************/
/********************************************************************/

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/Universidad/3º/Segundo Cuatrimestre/Procesadores de lenguaje/Práctica - PL/-PL-Practica1/LSpecification/lexical_specification.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comment = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\5\1\7\1\7\1\6\22\0\1\17\3\0\1\3"+
    "\2\0\1\11\1\12\1\15\1\13\1\62\1\56\1\1\1\55\1\0"+
    "\12\2\1\53\1\54\1\60\1\57\1\61\2\0\1\47\1\4\1\51"+
    "\1\4\1\44\1\4\1\45\1\52\1\41\2\10\1\50\1\10\1\42"+
    "\3\10\1\46\1\10\1\43\6\10\4\0\1\10\1\0\1\24\1\26"+
    "\1\33\1\32\1\27\1\40\1\23\1\10\1\30\3\10\1\25\1\31"+
    "\1\22\1\20\1\10\1\21\1\34\1\35\1\37\1\36\4\10\1\14"+
    "\1\0\1\16\7\0\1\7\u1fa2\0\1\7\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\0\1\2\2\3\2\0\1\4"+
    "\1\5\1\6\1\7\15\0\1\2\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\0\1\20\1\2"+
    "\2\0\1\2\1\0\1\2\2\21\1\0\1\21\1\22"+
    "\14\21\1\23\1\24\1\25\1\26\1\2\1\0\2\27"+
    "\1\30\1\21\1\31\1\32\1\21\1\33\1\34\1\35"+
    "\1\21\1\36\4\21\1\27\6\21\1\37\3\21\1\40"+
    "\1\41\10\21\1\42\2\21\1\43\2\21\1\44\1\21"+
    "\1\45\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\u0198\0\u01cb\0\u01fe\0\u0132\0\u0132\0\u0132\0\u0231\0\u0264"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u0132\0\u0132\0\u0132"+
    "\0\u0132\0\u052e\0\u0561\0\146\0\u0594\0\u0132\0\u05c7\0\u05fa"+
    "\0\u062d\0\u0660\0\u0693\0\u06c6\0\377\0\u0198\0\u06f9\0\u072c"+
    "\0\u0198\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\u0132\0\u0132\0\u0132"+
    "\0\u0132\0\u09c3\0\u09f6\0\u062d\0\u0660\0\u06f9\0\u0a29\0\u0198"+
    "\0\u0198\0\u0a5c\0\u0198\0\u0198\0\u0198\0\u0a8f\0\u0198\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u09f6\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27"+
    "\0\u0c5a\0\u0c8d\0\u0198\0\u0cc0\0\u0cf3\0\u0d26\0\u0198\0\u0198"+
    "\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0198\0\u0ef1\0\u0f24\0\u0198\0\u0f57\0\u0f8a\0\u0198\0\u0fbd"+
    "\0\u0198\0\u0198";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\7\1\10\1\0"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\0\1\7"+
    "\1\17\1\11\1\20\1\11\1\21\1\22\1\23\1\24"+
    "\1\11\1\25\1\26\1\27\2\11\1\30\1\11\1\31"+
    "\1\32\2\11\1\6\1\11\1\33\1\6\1\11\1\34"+
    "\1\11\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\13\0\1\45\2\0\1\46\46\0\1\47\1\0"+
    "\1\50\37\0\1\50\2\0\1\50\1\0\1\50\11\0"+
    "\2\51\1\4\1\51\1\52\3\0\34\51\1\52\2\51"+
    "\1\52\1\51\1\52\11\51\1\0\1\53\1\54\1\0"+
    "\1\54\37\0\1\54\2\0\1\54\1\0\1\54\10\0"+
    "\1\53\2\51\1\55\1\51\1\55\3\0\1\56\7\51"+
    "\24\56\1\55\2\56\1\55\1\56\1\55\1\56\10\51"+
    "\70\0\1\7\57\0\1\56\1\0\1\56\3\0\1\56"+
    "\7\0\33\56\10\0\63\57\13\0\1\15\51\0\1\56"+
    "\1\0\1\56\3\0\1\56\7\0\1\56\1\60\31\56"+
    "\12\0\1\56\1\0\1\56\3\0\1\56\7\0\1\56"+
    "\1\61\31\56\12\0\1\56\1\0\1\56\3\0\1\56"+
    "\7\0\11\56\1\62\21\56\12\0\1\56\1\0\1\56"+
    "\3\0\1\56\7\0\2\56\1\63\30\56\12\0\1\56"+
    "\1\0\1\56\3\0\1\56\7\0\7\56\1\64\23\56"+
    "\12\0\1\56\1\0\1\56\3\0\1\56\7\0\11\56"+
    "\1\65\21\56\12\0\1\56\1\0\1\56\3\0\1\56"+
    "\7\0\2\56\1\66\30\56\12\0\1\56\1\0\1\56"+
    "\3\0\1\56\7\0\10\56\1\67\22\56\12\0\1\56"+
    "\1\0\1\56\3\0\1\56\7\0\2\56\1\70\30\56"+
    "\12\0\1\56\1\0\1\56\3\0\1\56\7\0\4\56"+
    "\1\71\26\56\12\0\1\56\1\0\1\56\3\0\1\56"+
    "\7\0\17\56\1\72\13\56\12\0\1\56\1\0\1\56"+
    "\3\0\1\56\7\0\22\56\1\73\10\56\12\0\1\56"+
    "\1\0\1\56\3\0\1\56\7\0\24\56\1\74\6\56"+
    "\10\0\2\51\1\55\1\51\1\55\3\0\1\56\7\51"+
    "\24\56\1\55\2\56\1\55\1\56\1\55\1\75\10\51"+
    "\57\0\1\76\62\0\1\77\1\0\1\100\60\0\1\101"+
    "\20\0\1\46\45\0\2\51\1\102\1\51\1\103\3\0"+
    "\34\51\1\103\2\51\1\103\1\51\1\103\13\51\1\103"+
    "\1\51\1\103\3\0\34\51\1\103\2\51\1\103\1\51"+
    "\1\103\11\51\2\0\1\104\1\0\1\104\37\0\1\104"+
    "\2\0\1\104\1\0\1\104\11\0\2\51\1\105\1\51"+
    "\1\54\3\0\34\51\1\54\2\51\1\54\1\51\1\54"+
    "\11\51\2\0\1\50\1\0\1\50\37\0\1\50\2\0"+
    "\1\50\1\0\1\50\11\0\2\51\1\54\1\51\1\54"+
    "\3\0\34\51\1\54\2\51\1\54\1\51\1\54\11\51"+
    "\11\57\1\106\51\57\2\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\2\56\1\107\30\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\12\56\1\110\20\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\12\56\1\111"+
    "\20\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\3\56\1\112\27\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\12\56\1\113\20\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\15\56\1\114\15\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\16\56\1\115"+
    "\14\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\11\56\1\116\21\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\1\56\1\117\31\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\11\56\1\120\21\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\23\56\1\121"+
    "\7\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\27\56\1\122\3\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\27\56\1\123\3\56\10\0\2\51\1\102"+
    "\1\51\1\124\3\0\34\51\1\124\2\51\1\124\1\51"+
    "\1\124\13\51\1\124\1\51\1\124\3\0\34\51\1\124"+
    "\2\51\1\124\1\51\1\124\11\51\2\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\3\56\1\125\7\56\1\126"+
    "\17\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\10\56\1\127\22\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\14\56\1\130\16\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\13\56\1\131\17\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\24\56\1\132"+
    "\6\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\30\56\1\133\2\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\26\56\1\134\4\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\1\56\1\135\31\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\7\56\1\136"+
    "\23\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\11\56\1\137\21\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\15\56\1\140\15\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\15\56\1\141\15\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\25\56\1\142"+
    "\5\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\27\56\1\143\3\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\4\56\1\144\26\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\12\56\1\145\20\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\10\56\1\146"+
    "\22\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\24\56\1\147\6\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\31\56\1\150\1\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\5\56\1\151\25\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\17\56\1\152"+
    "\13\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\2\56\1\153\30\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\26\56\1\154\4\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\23\56\1\155\7\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\1\56\1\156"+
    "\31\56\12\0\1\56\1\0\1\56\3\0\1\56\7\0"+
    "\11\56\1\157\21\56\12\0\1\56\1\0\1\56\3\0"+
    "\1\56\7\0\24\56\1\160\6\56\12\0\1\56\1\0"+
    "\1\56\3\0\1\56\7\0\7\56\1\161\23\56\12\0"+
    "\1\56\1\0\1\56\3\0\1\56\7\0\26\56\1\162"+
    "\4\56\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\1\1\0\1\1\1\11\1\1\2\0\1\1"+
    "\3\11\15\0\2\1\4\11\3\1\1\0\1\11\1\1"+
    "\2\0\1\1\1\0\3\1\1\0\16\1\4\11\1\1"+
    "\1\0\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(sym.minus, yyline, yycolumn, yytext());
            }
          case 39: break;
          case 2: 
            { return new Symbol(sym.numeric_integer_const, yyline, yycolumn, yytext());
            }
          case 40: break;
          case 3: 
            { 
            }
          case 41: break;
          case 4: 
            { return new Symbol(sym.open_parenthesis, yyline, yycolumn, yytext());
            }
          case 42: break;
          case 5: 
            { return new Symbol(sym.multip, yyline, yycolumn, yytext());
            }
          case 43: break;
          case 6: 
            { System.out.println("Inicio de comentario");
			yybegin(comment);
            }
          case 44: break;
          case 7: 
            { return new Symbol(sym.closed_parenthesis, yyline, yycolumn, yytext());
            }
          case 45: break;
          case 8: 
            { return new Symbol(sym.two_points, yyline, yycolumn, yytext());
            }
          case 46: break;
          case 9: 
            { return new Symbol(sym.semicolon, yyline, yycolumn, yytext());
            }
          case 47: break;
          case 10: 
            { return new Symbol(sym.dot, yyline, yycolumn, yytext());
            }
          case 48: break;
          case 11: 
            { return new Symbol(sym.coma, yyline, yycolumn, yytext());
            }
          case 49: break;
          case 12: 
            { return new Symbol(sym.equal, yyline, yycolumn, yytext());
            }
          case 50: break;
          case 13: 
            { return new Symbol(sym.lt, yyline, yycolumn, yytext());
            }
          case 51: break;
          case 14: 
            { return new Symbol(sym.gt, yyline, yycolumn, yytext());
            }
          case 52: break;
          case 15: 
            { return new Symbol(sym.plus, yyline, yycolumn, yytext());
            }
          case 53: break;
          case 16: 
            { System.out.println("Fin de comentario");
			yybegin(YYINITIAL);
            }
          case 54: break;
          case 17: 
            { return new Symbol(sym.identifier, yyline, yycolumn, yytext());
            }
          case 55: break;
          case 18: 
            { return new Symbol(sym.or, yyline, yycolumn, yytext());
            }
          case 56: break;
          case 19: 
            { return new Symbol(sym.assignment, yyline, yycolumn, yytext());
            }
          case 57: break;
          case 20: 
            { return new Symbol(sym.le, yyline, yycolumn, yytext());
            }
          case 58: break;
          case 21: 
            { return new Symbol(sym.not_equal, yyline, yycolumn, yytext());
            }
          case 59: break;
          case 22: 
            { return new Symbol(sym.ge, yyline, yycolumn, yytext());
            }
          case 60: break;
          case 23: 
            { return new Symbol(sym.numeric_real_const, yyline, yycolumn, yytext());
            }
          case 61: break;
          case 24: 
            { return new Symbol(sym.string_const, yyline, yycolumn, yytext());
            }
          case 62: break;
          case 25: 
            { return new Symbol(sym.and, yyline, yycolumn, yytext());
            }
          case 63: break;
          case 26: 
            { return new Symbol(sym.mod, yyline, yycolumn, yytext());
            }
          case 64: break;
          case 27: 
            { return new Symbol(sym.end, yyline, yycolumn, yytext());
            }
          case 65: break;
          case 28: 
            { return new Symbol(sym.not, yyline, yycolumn, yytext());
            }
          case 66: break;
          case 29: 
            { return new Symbol(sym.div, yyline, yycolumn, yytext());
            }
          case 67: break;
          case 30: 
            { return new Symbol(sym.var, yyline, yycolumn, yytext());
            }
          case 68: break;
          case 31: 
            { return new Symbol(sym.real, yyline, yycolumn, yytext());
            }
          case 69: break;
          case 32: 
            { return new Symbol(sym.begin, yyline, yycolumn, yytext());
            }
          case 70: break;
          case 33: 
            { return new Symbol(sym.const_tok, yyline, yycolumn, yytext());
            }
          case 71: break;
          case 34: 
            { return new Symbol(sym.program, yyline, yycolumn, yytext());
            }
          case 72: break;
          case 35: 
            { return new Symbol(sym.integer, yyline, yycolumn, yytext());
            }
          case 73: break;
          case 36: 
            { return new Symbol(sym.function, yyline, yycolumn, yytext());
            }
          case 74: break;
          case 37: 
            { return new Symbol(sym.procedure, yyline, yycolumn, yytext());
            }
          case 75: break;
          case 38: 
            { return new Symbol(sym.character, yyline, yycolumn, yytext());
            }
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
