
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 2;
  public static final int function = 8;
  public static final int plus = 25;
  public static final int numeric_real_const = 35;
  public static final int mod = 29;
  public static final int minus = 26;
  public static final int gt = 21;
  public static final int coma = 15;
  public static final int not_equal = 24;
  public static final int identifier = 33;
  public static final int begin = 3;
  public static final int real = 10;
  public static final int ge = 23;
  public static final int closed_parenthesis = 18;
  public static final int end = 4;
  public static final int assignment = 19;
  public static final int equal = 16;
  public static final int two_points = 12;
  public static final int var = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int lt = 20;
  public static final int or = 30;
  public static final int procedure = 7;
  public static final int integer = 9;
  public static final int le = 22;
  public static final int multip = 27;
  public static final int and = 31;
  public static final int not = 32;
  public static final int numeric_integer_const = 34;
  public static final int character = 11;
  public static final int string_const = 36;
  public static final int div = 28;
  public static final int semicolon = 13;
  public static final int const_tok = 5;
  public static final int dot = 14;
  public static final int open_parenthesis = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "program",
  "begin",
  "end",
  "const_tok",
  "var",
  "procedure",
  "function",
  "integer",
  "real",
  "character",
  "two_points",
  "semicolon",
  "dot",
  "coma",
  "equal",
  "open_parenthesis",
  "closed_parenthesis",
  "assignment",
  "lt",
  "gt",
  "le",
  "ge",
  "not_equal",
  "plus",
  "minus",
  "multip",
  "div",
  "mod",
  "or",
  "and",
  "not",
  "identifier",
  "numeric_integer_const",
  "numeric_real_const",
  "string_const"
  };
}

